services:
#  |---------POSTGRES---------|
  postgres:
    image: postgres:15-alpine
    container_name: kyc_postgres
    environment:
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: kyc_password
      POSTGRES_DB: kyc_db
    ports:
      - "5433:5432"
    restart: unless-stopped
#  |---------PROMETHEUS---------|
  prometheus:
    image: prom/prometheus:latest
    container_name: ktc_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  #  |---------GRAFANA---------|
  grafana:
    image: grafana/grafana:latest
    container_name: kyc_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  kafka:
    image: apache/kafka:3.7.0
    container_name: kyc_kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093

      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
#  |---------KYC_APP---------|
  app:
    build: .
    container_name: kyc_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/kyc_db
      - KAFKA_URL=kafka:9092
    depends_on:
      - postgres
    restart: always
